language: groovy
jdk:
- openjdk8
sudo: false
branches:
  only:
  - master
  - develop
before_install:
- cd $TRAVIS_BUILD_DIR
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
after_success:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && travis_retry ./gradlew publish --stacktrace --info '
env:
  global:
    - secure: GtjSVGpDzKZN5IU6ZXkgMXw0z8HlGofBjuNd64N7nYOTovJL/h2/ipgBa2CTmY3kvgFVCQDRzEQU60kX295I0h/EyR4tgxTzpPMvHL9htt52qUeQJIi73thDFImPlvNYxKnKiql0JXoDW6dgNobGWK4KSh11xY/sr5+oYSa9ylbmtGw2wgKHAvBqfwhhbIEt2/yh3FLx9Pu0bmrXNCSjFF/zQJwn1MIfQUmVV9cimt095zSNbx+o1DWaQFCwMuI/mZPdxLFIDaQ89X8UvNPa2fFxJC/Jml4CR0bTyqfrb6FfRTmvM56JVn2da2LqSmd41N9kTYkvw7lhD6/SoiN8PbraWBVvTZo/2ighI56jXyb7Zr58NPs3MXtm7w5VAEM9DJTi2fwlfIjvMTpaFvTbOUrOGzLQE8n6DxWTjWD6YjLabY9mZYnwuF0UxtQn0LHRpEoTDXr2DhArRYwhBnySDJWiM+hVoUrTZo0h4yC49WEk6l8rllD2Tq17HwpboTCK3YrmVHnK+P/nhAQhVw3JCrF8PWY2i4obIh3QknonurAnLy3g1pWP9MVnTJLexh/xgtQqMLD6w8CehobNnULdVKaCKc1wZcBRh7Se+IENz0ds0K9jMHSi9VLrNofepEBNSufQp7ELD/kXEG0ARhVD12DgUxL3I29pvCYzAiQ6NyU=
    - secure: Uz19GCCUa+VxGWI1y19N+jIdXgn1L8NsaFn5WiSMJqYrbq0AOpQuosCKvRRxbTJjXNsyVWn1CwoaBtqgQCqpSg24lVrsIamH2lyb8IrEtCeSw8GI5pBnIxniIDnwsnjVDCpZVSOlskeVwFWKZ/m3CZada2vaja5OkArv51IqJaCMiMcdprVJ3JkvrsGaYD2P13auCYfSlZkKcZoEXV/unN9Flcj/TwN66yrq5yl8WYl92OmtNojoIS5WEn9FOJrmx7P8MLQkhdpIf1nDPmarabSSbSZIXqFsP4O4Q3OTqGkeTmzDoAJl3Cd79lyWDb3v134yfY0/TDRXY/zht8EORsYA+F3bNNZYiEmcjhUhyUx2ZP/F6wkULBjHdN8KUAg6DMdMgLvD4KnscnfPYcbYiq7qJ3cycuvVXWkh8uU4TFjfSOzRw7ZJCE6yfnyTkK98u6HUWQL6NKjDqe3L8TLok0dAQOFfkencMDnS0d5697kxSdiRZ7DMh1z6UsGWZvgwXABe407T/PQ0aTER2GhGwGeZ9K57Jgy1bzKVHyffOhYr+4ze2lCOa+2Me1i515sBDunW1TW97YAhn35VVUljkTizLYV4u68zncqGKfHDioHTBR3z+aCwEIN6Pox/7XcuVmg7qbLXgctDFTafu1bKIPy5Hb+JyelYNdODqsJS1DY=
